import type { Metadata } from "next";

import SideBar from "@/components/SideBar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <div className="flex min-h-screen w-screen bg-white">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
