import type { Metadata } from "next";
import { redirect } from "next/navigation";

import { createSessionClient, getUser } from "@/lib/appwrite/server";
import { DATABASE_ID, USERS_COLLECTION_ID } from "@/lib/env";

import ConnectToSocket from "@/components/ConnectToSocket";
import SideBar from "@/components/SideBar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { account, databases } = await createSessionClient();
  const user = await getUser(account);

  if (!user) redirect("/login");

  let err: AppwriteException | null = null;
  let avatar_image: string | null = null;

  try {
    const { avatar_image: image } = await databases.getDocument(
      DATABASE_ID,
      USERS_COLLECTION_ID,
      user.$id,
    );

    avatar_image = image;
  } catch (e) {
    // handle the error later
    err = e as AppwriteException;
  }

  if (err) {
    redirect(`/error?errorMessage=${err.message}`);
  }

  if (!avatar_image) {
    redirect(`/error`);
  }

  return (
    <>
      <ConnectToSocket />
      <SideBar
        avatar_image={avatar_image}
        username={user.name}
        userEmail={user.email}
      />
      <div
        className=" bg-white transition"
        style={{
          transitionProperty: "margin-left",
          transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
        }}
      >
        <Toaster />
        {children}
      </div>
    </>
  );
}
