FROM node:latest

WORKDIR /drizzle-studio

RUN npm init -y && \
    npm install drizzle-orm pg drizzle-kit typescript @types/node

COPY ./drizzle.config.ts .

COPY ./src/db/. .

COPY ./src/db/models/. ./schemas/.

CMD npx drizzle-kit studio --port=4001 --config=drizzle.config.ts
