export const BUCKET_ID = process.env.AVATAR_IMAGES_BUCKET_ID!;
export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;

export const DATABASE_ID = process.env.DATABASE_ID!;
export const USERS_COLLECTION_ID = process.env.USERS_COLLECTION_ID!;
export const CONVERSATIONS_COLLECTION_ID =
  process.env.CONVERSATIONS_COLLECTION_ID!;
export const USER_CONVERSATIONS_COLLECTION_ID =
  process.env.USER_CONVERSATIONS_COLLECTION_ID!;
export const MESSAGES_COLLECTION_ID = process.env.MESSAGES_COLLECTION_ID!;
