name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install

      - name: Run formatter
        run: turbo run format

      - name: Run linter
        run: turbo run lint

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Create the Frontend and Backend docker images
        run: |
          docker compose up build frontend backend

          docker tag pentest-app_frontend ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker tag pentest-app_backend ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
        
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker compose down
            docker compose pull
            docker compose up -d --force-recreate
            docker image prune -f